### ISSUE TITLE
Any Plans on starting kubernetes chart

### ISSUE THREAD

**Issue by jensenity** [ubisoft/mobydq#352]
Just wondering if mobydq is planning on start a chart to run mobydq on k8s cluster.

I've been testing it and would love to contribute in it.

Please let me know.

**Comment by alexisrolland** [comment]
Hi @jensenity !

Glad to see you have been testing MobyDQ. I understand the idea about running it on K8s but I am not really to understand what you mean by « start a chart »?

Right now there was no plan to work on this but I will look into the feasibility and if it’s relatively easy I may give it a try. In the meantime if you wish to contribute you are very welcome to do so! I believe you can fork, update and push merge requests.

Best,
Alexis
